### ISSUE TITLE
Deploy issue with database

### ISSUE THREAD

**Issue by aarongustafson** [vfalconi/mini-jxnwater#1]
http://mini-jxnwater-info-10kapart2016.azurewebsites.net/

Are you using JSON or SQLite for your data store?

**Comment by vfalconi** [comment]
Whoops. JSON, but I forgot to remove the database class from the autoload. Fixing now.

**Comment by aarongustafson** [comment]
Deployed. Will publish in a few minutes.

**Comment by vfalconi** [comment]
Oh, crap. It looks like modrewrite isn't enabled on the server.

http://mini-jxnwater-info-10kapart2016.azurewebsites.net/2
